# Generated by Django 4.0.6 on 2022-07-23 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Incorrect mobile number.', regex='(0|91)?[7-9][0-9]{9}$')])),
                ('address', models.TextField(max_length=1000)),
            ],
        ),
    ]
